Feature/[ #82 ] Complete seven button UI & Add DadInitController
DeveloperAcademy-POSTECH/MC3-Team6-HaKenLuRooCo pull request #85
Opened 2022-07-28 08:52 UTC by luminouxx

## 개요
Seven Button의 지옥에서 탈출하고자 합니다.
- SevenButton UI 완성
- DadInitViewController를 추가했습니다.

<br/>

## 작업사항
### 작업 사항
- SevenButton이 3개까지만 선택되도록 했습니다.
- 버튼의 Customizing을 완료했습니다.

### References
- 없습니다.

### 테스트 결과 (스크린샷, GIF, 샘플 API 등 결과물)

![Jul-28-2022 17-48-54](https://user-images.githubusercontent.com/81943525/181463661-993c1abd-96e9-47e1-b819-1b6801deb32e.gif)

<br/>

## 그외
### 리뷰 포인트
ex) 리뷰받고 싶은 내용, 고민한 내용  등에 대해 적어주세요
- 코드 스타일
- 조금 하드하게 코드를 짠 것 같아 더 나은 방안이 있다면 알려주세요

### 진행 예정 사항
ex) 작업 진행 예정사항 및 개선하고 싶은 내용이 있다면 추가 해주세요
- [ ] About Us

2022-07-28 11:25 UTC, Rookie0031 requested changes
### 루미 고생했습니다!!!!!

이제는 탈출합시다... 우당탕탕 코드도 잘 만져주셧네요 굿굿입니다!!
버튼 아래 dot 넣는코드 수정해서 해주시면 될 거 같습니다! 그럼 이 뷰는 거의 마무리되고 버그 테스팅만 하면 될거같네요

2022-07-28 11:25 UTC, Rookie0031 commented on TodayAnbu/Sources/Controllers/DadInitViewController.swift
> +            let tempButtonIndex = recognizer.view!.tag
temporary로 인덱스를 한번 더 설정해주기만 하면 되는거엿군요!! 딱 맞게 잘 넣어주셧네요!! 굿굿

2022-07-28 11:25 UTC, Rookie0031 commented on TodayAnbu/Sources/Controllers/DadInitViewController.swift
> +            horizontalStack.subviews.forEach({$0.layer.borderWidth = 0 })
##  Request
horizontalStack.subviews.forEach({$0.layer.borderWidth = 0 })
이 부분은 이제 없어져도 괜찮습니다!! 테두리에 노란색을 줬던 걸 초기화하는 건데 이제 밑에다 dot 레이블을 넣을거라서 빼주시면 됩니다!

2022-07-28 11:25 UTC, Rookie0031 commented on TodayAnbu/Sources/Controllers/DadInitViewController.swift
> +                horizontalStack.subviews[buttonIndex].layer.borderWidth = 3
## Request
#### 밑에 점 찍는 부분은 두줄만 바꿔주시면됩니다!

horizontalStack.subviews[buttonIndex].layer.borderWidth = 3
horizontalStack.subviews[buttonIndex].layer.borderColor = CGColor(red: 255, green: 120, blue: 0, alpha: 1)
================ 위 두 줄의 코드를 삭제해주시고 대신 그 자리에 아래 두줄 코드를 넣어주세요!  ================== 
let stack = horizontalStack.subviews[buttonIndex] as? UIStackView
stack?.addArrangedSubview(dot)

subView메소드를 통해 horizontalStackView의 하위뷰에 접근할 수 있습니다. 근데 subView는 UIView형태로 가져오기 때문에 이를 다시 UIStackView로 변환한 다음 다시 dot (버튼 밑에 점)을 넣어주는 구조입니다!

2022-07-28 11:28 UTC, Rookie0031 commented
## Bug Report
#### 루미 근데 버그를 하나 발견햇어요.. 지금 텍스트 필드에 휴대폰 번호 11자리를 넣고 버튼을 띄운 상태는 아래와 같은데

![Simulator Screen Shot - iPhone 13 - 2022-07-28 at 20 23 22](https://user-images.githubusercontent.com/103009135/181494091-9c79c244-f310-4225-ad6e-8ec8a1d08661.png)

#### 여기서 다시 휴대폰 번호 텍스트 필드를 클릭하고 번호를 추가로 입력해버리면 아래 뷰가 없어져 버립니다
![Simulator Screen Shot - iPhone 13 - 2022-07-28 at 20 23 28](https://user-images.githubusercontent.com/103009135/181494290-f8e89c53-db5b-4f78-9004-ddb57deba96b.png)

이거 혹시 왜 이런지 아실까요??? 간단한거면 위 코드 고치면서 같이 고쳐주시면되고 생각보다 복잡하면 낼 이야기합시다!! 
몸 아픈데 고생많네요 홧팅입니다

2022-07-28 11:28 UTC, luminouxx commented on TodayAnbu/Sources/Boards/Base.lproj/Main.storyboard
> -                        <rect key="frame" x="0.0" y="0.0" width="414" height="842"/>
추측하기로는 modal로 바꿔서 그런 것이 아닐까 싶습니다....

2022-07-28 11:32 UTC, luminouxx commented on TodayAnbu/Sources/Controllers/DadInitViewController.swift
> +                horizontalStack.subviews[buttonIndex].layer.borderWidth = 3
네 반영했습니다!

2022-07-28 11:34 UTC, luminouxx commented
> 

아마 저희 로직이 Done 버튼을 눌렀을 때 -> validation Check -> 아래의 StackView 보여주기 순서여서 그런 것 같아요 ㅎ

2022-07-29 00:11 UTC, Rookie0031 approved these changes
## 고생하셨습니다!!

2022-07-29 00:11 UTC, merged